version: '3.5'

services:
  api:
    container_name: api_container
    build:
      context: ./
    environment:
      DB_CONNECTION: "User ID=CatalogoProduto;Password=123456789;Host=postgres;Port=5432;Database=CatalogoProduto;Pooling=true;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORT: https://+:3001
      ASPNETCORE_URLS: http://+:3000
    ports:
      - "3001:3001"
      - "3000:3000"
    networks:
      - catalogoProduto
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: CatalogoProduto
      POSTGRES_PASSWORD: 123456789
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - catalogoProduto
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - catalogoProduto
    restart: unless-stopped

networks:
  catalogoProduto:
    driver: bridge

volumes:
  postgres:
  pgadmin: